# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-cageseq-1.0.2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.9.2
  - conda-forge::markdown=3.3.4
  - conda-forge::pymdown-extensions=8.1.1
  - conda-forge::pygments=2.8.1
  - bioconda::bedtools=2.30.0
  - bioconda::bowtie=1.3.0
  - bioconda::cutadapt=3.4
  - bioconda::fastqc=0.11.9
  - bioconda::multiqc=1.10.1
  - bioconda::paraclu=10
  - bioconda::rseqc=4.0.0
  - bioconda::samtools=1.12
  - bioconda::star=2.7.8a # Don't upgrade me - 2.7X indices incompatible with iGenomes.
  - bioconda::sortmerna=4.3.2
  - bioconda::ucsc-bedgraphtobigwig=377
